#!/usr/bin/env node
/**
 * Blueprint: content generation pipeline runner
 * Usage in Digital Twin: route to pipelineContent()
 * Default mode: template generator without external provider dependency.
 * Network calls are optional and configured by env.
 */

require('dotenv').config();

async function generateText({ topic, audience, tone = 'professional', length = 'medium' }) {
  const prompt = buildPrompt({ topic, audience, tone, length });

  if (process.env.CONTENT_PROVIDER === 'openai') {
    return await callOpenAI(prompt);
  }
  // Default: deterministic local draft
  return localDraft(prompt);
}

function buildPrompt({ topic, audience, tone }) {
  return `${tone} briefing on "${topic}" for ${audience}. Include: Context, Evidence, Implications, Action summary.`;
}

async function callOpenAI(prompt) {
  if (!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY missing');

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      messages: [
        { role: 'system', content: 'You are a revenue content engineer.' },
        { role: 'user', content: prompt }
      ],
      temperature: 0.4
    })
  });

  if (!res.ok) throw new Error('OpenAI provider error: ' + res.status);
  const data = await res.json();
  return data?.choices?.[0]?.message?.content || '';
}

function localDraft(prompt) {
  const title = prompt.replace('Include:', '').substring(0, 120) || 'Content draft';
  return `[LOCAL DRAFT]\n\n${title}\n\nGenerated by Digital Twin offline template.`;
}

module.exports = { generateText };
